spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/culinary_craft_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  codec:
    max-in-memory-size: 1MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      default-schema: public
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  docker:
    compose:
      enabled: false

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  mail:
    username: culinarycraft48@gmail.com
    password: fkzz gmow iopc krhc

  constants:
    companyName: "Culinary Craft"

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

apiVersion: "/api/v1"

admin:
  password: 1234

server:
  port: 8081